services:
  orderflow.apphost:
    image: orderflow.apphost
    build:
      context: .
      dockerfile: OrderFlow.AppHost/Dockerfile
    ports:
      - "5900:5000"

  orderflow.database:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "orderflow"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    container_name: orderflow.database

